name: Admin Arif deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "."
        target: "/var/www/admin.arif.uz"

    - name: Command using from script
      uses: appleboy/ssh-action@master
      env:
        DISABLE_ESLINT_PLUGIN: "true"
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: DISABLE_ESLINT_PLUGIN
        script_stop: true
        script: |
          git --work-tree=/var/www/admin.arif.uz --git-dir=/var/www/admin.arif.uz/.git clean -f .
          npm --prefix /var/www/admin.arif.uz/ install /var/www/admin.arif.uz/
          npm --prefix /var/www/admin.arif.uz/ run build
          sh /home/devops/adminarif_front.sh "${{ github.event.head_commit.message }}"